// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MotionGlow.DAL.Data;

#nullable disable

namespace MotionGlow.DAL.Migrations
{
    [DbContext(typeof(MotionGlowDbContext))]
    [Migration("20240515065559_Encapsulation enforce")]
    partial class Encapsulationenforce
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MotionGlow.DAL.Models.ESP32_Device", b =>
                {
                    b.Property<int>("DeviceID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("DeviceID")
                        .HasName("PK__ESP32_De__49E123317F6364D6");

                    b.ToTable("ESP32_Device");
                });

            modelBuilder.Entity("MotionGlow.DAL.Models.PIRSensor", b =>
                {
                    b.Property<int>("SensorID")
                        .HasColumnType("int");

                    b.Property<int?>("DeviceID")
                        .HasColumnType("int");

                    b.HasKey("SensorID")
                        .HasName("PK__PIRSenso__D809841AE0FAE2E3");

                    b.HasIndex("DeviceID");

                    b.ToTable("PIRSensor");
                });

            modelBuilder.Entity("MotionGlow.DAL.Models.SensorActivityLog", b =>
                {
                    b.Property<int>("LogID")
                        .HasColumnType("int");

                    b.Property<int?>("DeviceID")
                        .HasColumnType("int");

                    b.Property<decimal?>("Distance")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int?>("PIRSensorID")
                        .HasColumnType("int");

                    b.Property<int?>("SoundLevel")
                        .HasColumnType("int");

                    b.Property<int?>("SoundSensorID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime");

                    b.HasKey("LogID")
                        .HasName("PK__SensorAc__5E5499A8770AC7AC");

                    b.HasIndex("DeviceID");

                    b.HasIndex("PIRSensorID");

                    b.HasIndex("SoundSensorID");

                    b.ToTable("SensorActivityLog");
                });

            modelBuilder.Entity("MotionGlow.DAL.Models.SoundSensor", b =>
                {
                    b.Property<int>("SensorID")
                        .HasColumnType("int");

                    b.Property<int?>("DeviceID")
                        .HasColumnType("int");

                    b.HasKey("SensorID")
                        .HasName("PK__SoundSen__D809841A97688CF6");

                    b.HasIndex("DeviceID");

                    b.ToTable("SoundSensor");
                });

            modelBuilder.Entity("MotionGlow.DAL.Models.PIRSensor", b =>
                {
                    b.HasOne("MotionGlow.DAL.Models.ESP32_Device", "Device")
                        .WithMany("PIRSensor")
                        .HasForeignKey("DeviceID")
                        .HasConstraintName("FK__PIRSensor__Devic__4E88ABD4");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("MotionGlow.DAL.Models.SensorActivityLog", b =>
                {
                    b.HasOne("MotionGlow.DAL.Models.ESP32_Device", "Device")
                        .WithMany("SensorActivityLog")
                        .HasForeignKey("DeviceID")
                        .HasConstraintName("FK__SensorAct__Devic__5165187F");

                    b.HasOne("MotionGlow.DAL.Models.PIRSensor", "PIRSensor")
                        .WithMany("SensorActivityLog")
                        .HasForeignKey("PIRSensorID")
                        .HasConstraintName("FK__SensorAct__PIRSe__534D60F1");

                    b.HasOne("MotionGlow.DAL.Models.SoundSensor", "SoundSensor")
                        .WithMany("SensorActivityLog")
                        .HasForeignKey("SoundSensorID")
                        .HasConstraintName("FK__SensorAct__Sound__52593CB8");

                    b.Navigation("Device");

                    b.Navigation("PIRSensor");

                    b.Navigation("SoundSensor");
                });

            modelBuilder.Entity("MotionGlow.DAL.Models.SoundSensor", b =>
                {
                    b.HasOne("MotionGlow.DAL.Models.ESP32_Device", "Device")
                        .WithMany("SoundSensor")
                        .HasForeignKey("DeviceID")
                        .HasConstraintName("FK__SoundSens__Devic__4BAC3F29");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("MotionGlow.DAL.Models.ESP32_Device", b =>
                {
                    b.Navigation("PIRSensor");

                    b.Navigation("SensorActivityLog");

                    b.Navigation("SoundSensor");
                });

            modelBuilder.Entity("MotionGlow.DAL.Models.PIRSensor", b =>
                {
                    b.Navigation("SensorActivityLog");
                });

            modelBuilder.Entity("MotionGlow.DAL.Models.SoundSensor", b =>
                {
                    b.Navigation("SensorActivityLog");
                });
#pragma warning restore 612, 618
        }
    }
}
