// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MotionGlow.DAL.Data;

#nullable disable

namespace MotionGlow.DAL.Migrations
{
    [DbContext(typeof(MotionGlowDbContext))]
    [Migration("20240607070731_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MotionGlow.DAL.Models.ESP32_Device", b =>
                {
                    b.Property<int>("DeviceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceID"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("DeviceID")
                        .HasName("PK__ESP32_De__49E1233103832F04");

                    b.HasIndex(new[] { "DeviceName" }, "idx_DeviceName");

                    b.HasIndex(new[] { "DeviceType" }, "idx_DeviceType");

                    b.HasIndex(new[] { "Location" }, "idx_Location");

                    b.ToTable("ESP32_Device");
                });

            modelBuilder.Entity("MotionGlow.DAL.Models.PIRSensor", b =>
                {
                    b.Property<int>("SensorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SensorID"));

                    b.Property<int>("DeviceID")
                        .HasColumnType("int");

                    b.HasKey("SensorID")
                        .HasName("PK__PIRSenso__D809841A74EE4F65");

                    b.HasIndex("DeviceID");

                    b.ToTable("PIRSensor");
                });

            modelBuilder.Entity("MotionGlow.DAL.Models.SensorActivityLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<int>("DeviceID")
                        .HasColumnType("int");

                    b.Property<decimal?>("Distance")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("PIRSensorID")
                        .HasColumnType("int");

                    b.Property<int?>("SoundLevel")
                        .HasColumnType("int");

                    b.Property<int>("SoundSensorID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime");

                    b.HasKey("LogID")
                        .HasName("PK__SensorAc__5E5499A86D16828D");

                    b.HasIndex("DeviceID");

                    b.HasIndex("PIRSensorID");

                    b.HasIndex("SoundSensorID");

                    b.ToTable("SensorActivityLog");
                });

            modelBuilder.Entity("MotionGlow.DAL.Models.SoundSensor", b =>
                {
                    b.Property<int>("SensorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SensorID"));

                    b.Property<int>("DeviceID")
                        .HasColumnType("int");

                    b.HasKey("SensorID")
                        .HasName("PK__SoundSen__D809841A09F0AE66");

                    b.HasIndex("DeviceID");

                    b.ToTable("SoundSensor");
                });

            modelBuilder.Entity("MotionGlow.DAL.Models.PIRSensor", b =>
                {
                    b.HasOne("MotionGlow.DAL.Models.ESP32_Device", "Device")
                        .WithMany("PIRSensor")
                        .HasForeignKey("DeviceID")
                        .IsRequired()
                        .HasConstraintName("FK__PIRSensor__Devic__74AE54BC");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("MotionGlow.DAL.Models.SensorActivityLog", b =>
                {
                    b.HasOne("MotionGlow.DAL.Models.ESP32_Device", "Device")
                        .WithMany("SensorActivityLog")
                        .HasForeignKey("DeviceID")
                        .IsRequired()
                        .HasConstraintName("FK__SensorAct__Devic__778AC167");

                    b.HasOne("MotionGlow.DAL.Models.PIRSensor", "PIRSensor")
                        .WithMany("SensorActivityLog")
                        .HasForeignKey("PIRSensorID")
                        .IsRequired()
                        .HasConstraintName("FK__SensorAct__PIRSe__797309D9");

                    b.HasOne("MotionGlow.DAL.Models.SoundSensor", "SoundSensor")
                        .WithMany("SensorActivityLog")
                        .HasForeignKey("SoundSensorID")
                        .IsRequired()
                        .HasConstraintName("FK__SensorAct__Sound__787EE5A0");

                    b.Navigation("Device");

                    b.Navigation("PIRSensor");

                    b.Navigation("SoundSensor");
                });

            modelBuilder.Entity("MotionGlow.DAL.Models.SoundSensor", b =>
                {
                    b.HasOne("MotionGlow.DAL.Models.ESP32_Device", "Device")
                        .WithMany("SoundSensor")
                        .HasForeignKey("DeviceID")
                        .IsRequired()
                        .HasConstraintName("FK__SoundSens__Devic__71D1E811");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("MotionGlow.DAL.Models.ESP32_Device", b =>
                {
                    b.Navigation("PIRSensor");

                    b.Navigation("SensorActivityLog");

                    b.Navigation("SoundSensor");
                });

            modelBuilder.Entity("MotionGlow.DAL.Models.PIRSensor", b =>
                {
                    b.Navigation("SensorActivityLog");
                });

            modelBuilder.Entity("MotionGlow.DAL.Models.SoundSensor", b =>
                {
                    b.Navigation("SensorActivityLog");
                });
#pragma warning restore 612, 618
        }
    }
}
